name: GitHub CI
run-name: CI Deployment 🚀
on: [push]
jobs:
  build:
   name: Build artifact
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Setup NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: cd DemoApi && dotnet restore
   
    - name: build
      run: cd DemoApi && dotnet build --no-restore

  test:
   name: Unit Tests
   needs: [build]
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Setup NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: cd DemoApi.Tests && dotnet restore
   
    - name: Run Unit Tests
      run: cd DemoApi.Tests && dotnet test